input_fields: &input_fields
  - one_offset_word_index
  - token
  - lemma
  - upos
  - ptb_pos
  - None
  - dep_head
  - dep_rel
  - None3
  - None4
  - source_file
  - part_number
  - zero_offset_word_index
  - token2
  - ptb_pos3
  - parse_bit
  - predicate_lemma
  - predicate_frameset_id
  - word_sense
  - speaker_author
  - named_entities

cache: &id_cache !WholeDatasetCache
  train_path: &train_path scripts/ontonotes_scripts/train.ontonotes.withdep.conll
  dev_path: &dev_path scripts/ontonotes_scripts/dev.ontonotes.withdep.conll
  test_path: &test_path scripts/ontonotes_scripts/test.ontonotes.withdep.conll

disk_reader: !OntonotesReader &disk_reader
  args: 
    - device: cuda:0
  train_path: *train_path 
  dev_path: *dev_path 
  test_path: *test_path 
  cache: *id_cache

dataset: !ListDataset
  args: 
    device: cuda:0
  data_loader: *disk_reader
  output_dataset: !AnnotationDataset
    args: 
      device: cuda:0
    task: !TokenClassificationTask
      args: 
        device: cuda:0
      task_name: ptb_pos
      input_fields: *input_fields
  input_datasets:
    - !HuggingfaceData
      args:
        device: cuda:0
      tokenizer_model_string: google/bert_uncased_L-12_H-768_A-12
      caches:
        train: !WholeDatasetCache
          dataset_path: *train_path
          task_name: *tokenizer_model_string
        dev: !WholeDatasetCache
          dataset_path: *dev_path
          task_name: *tokenizer_model_string
        test: !WholeDatasetCache
          dataset_path: *test_path
          task_name: *tokenizer_model_string
      wait_for_cache: true

model: !ListModel
  args: 
    device: cuda:0
  models:
    - !HuggingfaceModel
        args:
          device: cuda:0
        model_string: HaotianQi/8-768-en-s9273-distilbert
        trainable: False
        index: 2
    
probe: !OneWordLinearLabelProbe
  args:
    device: cuda:0
  model_dim: 768
  label_space_size: 50

regimen: !ProbeRegimen
  args:
    device: cuda:0
  max_epochs: 50
  params_path: params
  reporting_root: &reporting_root configs/round1/ptb_pos/bert768/layer0.yaml.results

reporter: !IndependentLabelReporter
  args:
    device: cuda:0
  reporting_root: *reporting_root
  reporting_methods:
    - label_accuracy
    - v_entropy
