input_fields: &id_input_fields
  - one_offset_word_index
  - token
  - None
  - ptb_pos
  - ptb_pos2
  - None2
  - dep_head
  - dep_rel
  - None3
  - None4
  - source_file
  - part_number
  - zero_offset_word_index
  - token2
  - ptb_pos3
  - parse_bit
  - predicate_lemma
  - predicate_frameset_id
  - word_sense
  - speaker_author
  - named_entities

disk_reader: !OntonotesReader &id_disk_reader
  args: 
    - device: cuda:0
  #train_path: &idtrainpath /u/scr/johnhew/ontonotes/vinfo-probing-internal/scripts/ontonotes_scripts/train.ontonotes.withdep.conll
  #dev_path: &iddevpath /u/scr/johnhew/ontonotes/vinfo-probing-internal/scripts/ontonotes_scripts/dev.ontonotes.withdep.conll
  #test_path: &idtestpath /u/scr/johnhew/ontonotes/vinfo-probing-internal/scripts/ontonotes_scripts/test.ontonotes.withdep.conll
  train_path: &idtrainpath scripts/ontonotes_scripts/small-train.ontonotes.withdep.conll
  dev_path: &iddevpath scripts/ontonotes_scripts/small-dev.ontonotes.withdep.conll
  test_path: &idtestpath scripts/ontonotes_scripts/small-test.ontonotes.withdep.conll
  cache: None

dataset: !ListDataset
  args: 
    device: cuda:0
  data_loader: *id_disk_reader
  output_dataset: !AnnotationDataset
    args: 
      device: cuda:0
    task: !TokenClassificationTask
      args: 
        device: cuda:0
      task_name: ptb_pos
      input_fields: *id_input_fields
  input_datasets:
    - !HuggingfaceData
      args:
        device: cuda:0
      model_string: google/bert_uncased_L-12_H-768_A-12
    - !HuggingfaceData
      args:
        device: cuda:0
      model_string: google/bert_uncased_L-12_H-768_A-12
        #    - !AnnotationDataset
        #      args: 
        #        device: cuda:0
        #      task: !TokenClassificationTask
        #        args:
        #          device: cuda:0
        #        task_name: token
        #        input_fields: *id_input_fields

model: !ListModel
  args: 
    device: cuda:0
  models:
    - !HuggingfaceModel
        args:
          device: cuda:0
        model_string: google/bert_uncased_L-12_H-768_A-12
        trainable: False
        index: 9
    - !HuggingfaceModel
        args:
          device: cuda:0
        model_string: google/bert_uncased_L-12_H-768_A-12
        trainable: False
        index: 0
          #    - !AnnotationModel
          #        args:
          #          device: cuda:0
          #        max_cardinality: 10000
          #        trainable: False
    
probe: !OneWordLinearLabelProbe
  args:
    device: cuda:0
  model_dim: 1536
  label_space_size: 50

regimen: !ProbeRegimen
  args:
    device: cuda:0
  max_epochs: 50
  params_path: .params
  reporting_root: configs/bert-control-for-embeddings-pos/bert_0control_layer9-pos.yaml.results

reporter: !IndependentLabelReporter
  args:
    device: cuda:0
  reporting_root: configs/bert-control-for-embeddings-pos/bert_0control_layer9-pos.yaml.results
  reporting_methods:
    - label_accuracy
    - v_entropy


